---

- name: test bigip_device_auth_ldap
  hosts: all
  gather_facts: no
  vars:
    an: 'ST&E'
    apit: 900
    apdt: yes
    apvi: yes
    ll: 'info'
    mc: 10
    rhth: no
    sport: 443
    scs: 'ECDHE-ECDSA-AES128-SHA256'
    sprot: '-all TLSv1.2 TLSv1.3'

  tasks:
    - name: example001
      bigip_device_httpd_report:
        auth_name: "{{ an }}"
        auth_pam_idle_timeout: "{{ apit }}"
        auth_pam_dashboard_timeout: "{{ apdt }}"
        auth_pam_validate_ip: "{{ apvi }}"
        log_level: "{{ ll }}"
        max_clients: "{{ mc }}"
        redirect_http_to_https: "{{ rhth }}"
        ssl_port: "{{ sport }}"
        ssl_cipher_suite: "{{ scs }}"
        ssl_protocols: "{{ sprot }}"
        provider:
          server: "{{ target_ip }}"
          #server: 192.168.122.63
          server_port: 8443
          user: admin
          password: admin
          validate_certs: no
      delegate_to: localhost
      register: returned_vars

    - name: cc001_auth_name
      ignore_errors: yes
      assert:
        that: 
          - returned_vars.ansible_facts.f5_http_settings.auth_name == an

    - name: v_60091
      ignore_errors: yes
      assert:
        that:
          - returned_vars.ansible_facts.f5_http_settings.max_clients == mc

# duplicate control for 60165 60167
    - name: v_60093
      ignore_errors: yes
      assert:
        that:
          - returned_vars.ansible_facts.f5_http_settings.auth_pam_idle_timeout == apit

    - name: v_60185a
      ignore_errors: yes
      assert:
        that:
          - returned_vars.ansible_facts.f5_http_settings.auth_pam_validate_ip == apvi

    - name: v_60185b
      ignore_errors: yes
      assert:
        that:
          - returned_vars.ansible_facts.f5_http_settings.auth_pam_dashboard_timeout == apdt

    - name: cc002_log_levels
      ignore_errors: yes
      assert:
        that:
          - returned_vars.ansible_facts.f5_http_settings.log_level == ll

    - name: cc003_http_redirect
      ignore_errors: yes
      assert:
        that:
          - returned_vars.ansible_facts.f5_http_settings.redirect_http_to_https == rhth

    - name: cc004_cipher_suite
      ignore_errors: yes
      assert:
        that:
          - returned_vars.ansible_facts.f5_http_settings.ssl_cipher_suite == scs

    - name: cc005_ssl_port
      ignore_errors: yes
      assert:
        that:
          - returned_vars.ansible_facts.f5_http_settings.ssl_port == sport

    - name: cc006_ssl_protocol
      ignore_errors: yes
      assert:
        that:
          - returned_vars.ansible_facts.f5_http_settings.ssl_protocols == sprot

    - name: report returned_vars
      debug:
        var: returned_vars
